[ISSUE-80]: update-ids func inserts ids into import statements
testomatio/check-tests pull request #91
Opened 2023-04-07 19:48 UTC by mykhailiukVitalii

Fixes for https://github.com/testomatio/check-tests/issues/80 
I have added additional import handling for ts & js files. Like 
```
const fixSuiteContent = (title, replace, content) => {
  const importLines = content.split('\n').filter(line => line.match(LINE_START_REGEX));

  if (importLines.length) {
    const testLines = content.split('\n').filter(line => !line.match(LINE_START_REGEX));
    const updatedTestLines = testLines.map(line => line.replace(title, replace));

    return [...importLines, ...updatedTestLines].join('\n');
  }

  return content.replace(title, replace);
};
```
+ I have added 3 unit tests to test the example described in the ticket.
![Screenshot-test-1](https://user-images.githubusercontent.com/82405549/230668407-b07307de-cb1c-44b9-87c1-5bbe1129b836.png)

2023-04-08 20:12 UTC, DavertMik requested changes
The approach is good.

Please rework it so when we replace suiteTitle we go line by line and ignore all lines that start with const/var/import

2023-04-08 20:12 UTC, DavertMik commented on tests/updateIds_test.js
> +
```suggestion
const userId = 1
```
Please check that this const won't be updated or reordered

2023-04-08 20:12 UTC, DavertMik commented on src/updateIds.js
> +    return [...importLines, ...updatedTestLines].join('\n');
Please place the lines in the very same order they appear in the source code
Do not reorder lines 
It is ok to ignore `const/import/var` lines but they must be placed on the same row position as they were before

2023-04-09 12:24 UTC, mykhailiukVitalii commented
@DavertMik I have updated changes + added a new unit test. Seem's like if I re-push to fork branch - the error for jobs is displayed again!

2023-04-10 01:12 UTC, DavertMik requested changes
Minor updates

2023-04-10 01:12 UTC, DavertMik commented on src/updateIds.js
> +    if (!line.match(LINE_START_REGEX)) {
```suggestion
   // ignore lines with kewords
    if (line.match(LINE_START_REGEX)) return;
```

let's simplify it a bit

2023-04-10 01:12 UTC, DavertMik commented on src/updateIds.js
> +  return [...updatedLines].join('\n');
```suggestion
  return updatedLines.join('\n');
```

2023-04-10 06:49 UTC, mykhailiukVitalii commented on src/updateIds.js
> +  return [...updatedLines].join('\n');
has been fixed

2023-04-10 06:49 UTC, mykhailiukVitalii commented on src/updateIds.js
> +    if (!line.match(LINE_START_REGEX)) {
You are right!... has been fixed

2023-04-10 06:50 UTC, mykhailiukVitalii commented
I have pushed latest changes

2023-04-10 11:31 UTC, DavertMik approved these changes

2023-04-10 11:34 UTC, DavertMik requested changes
Поверни мій код ) 
Можеш до нього тест додати
Бо такий кейс теж можливий

2023-04-10 11:34 UTC, DavertMik commented on src/updateIds.js
> -        for (let i = lineNumber; i < lines.length; i++) {
А ти міг би вернути цей код? 

Бо тут він хендлить такий ось кейс:

```
describe(
   'suite name'
   () => 

```

2023-04-10 13:35 UTC, mykhailiukVitalii commented on src/updateIds.js
> -        for (let i = lineNumber; i < lines.length; i++) {
Перевірив, все ок! + додав тести для такого випадку для cypress & playwright

2023-04-11 07:03 UTC, mykhailiukVitalii commented
@DavertMik I check your case + added a new unit-tests. Actual result -> all right.

2023-04-17 11:45 UTC, merged